---
title: "Country"
author: "Ghislaine KOSSONOU"
date: '2022-05-08'
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Importation des packages ####
library(tidyverse)
library(readxl)
install.packages("ggplot2")
library(ggplot2)
```

```{r}
library(dplyr)
library(tidyr)
```

```{r}
# Importation et lecture des données ####
Country <- read_excel("Country.xlsx")
View(Country)
names(Country)
#présentation des données des du tableau Country
(data = Country)
```


```{r}
# Sélection dans une table ####

Country [-(1:3), ] #sélection des infos du tableau de la ligne 1 #à la ligne 9
```
```{r}
# présentation du nombre de lignes comportant les # 3 villes 
Country$Population
Country$Annee
Country$Ville
```



```{r}
#dans le tableau Country, présentez les 3 premières lignes
head(Country, 3)
```

```{r}
#Afficher toutes les lignes du tableau Country
head(Country, 12)
```


```{r}
head(Country, 12)
  ggplot(data = Country) +    
    geom_histogram(aes(x=Annee))
bins = 30

```


```{r}
  ggplot (data = Country) +    
    geom_histogram(aes(x = Population))
      bins = 50
```


```{r}
Villes <- Country$Ville
  ggplot(Country) +
    geom_bar (aes(x=Villes))
      bins = 30
```


```{r}
Villes <- Country$Ville
  ggplot(Country) +
    geom_bar(aes(y = Villes)) +  geom_histogram(aes(x = Population))
          bins = 30
```

```{r}
Villes <- Country$Ville
  ggplot(Country) +
    geom_bar(aes(x = Villes)) +  geom_bar(aes(y = Population))
          bins = 30
```

#les valeurs de ville ne larche pas avec histogram

```{r}
Villes <- Country$Ville
  ggplot(Country) +
    geom_bar(aes(x = Villes)) +  geom_histogram(aes(y = Annee))
          bins = 30
          #diagramme étrange à revoir
```


```{r}
# "slice" sélectionne les lignes du tableau selon #leurs positions
slice(Country, 3)
```
```{r}
slice(Country, 1: 6)
#sélection des 6 premières lignes du tableau
```


```{r}
slice_tail(Country, n = 4)
#selection des 4 dernières lignes
```
```{r}
slice_head(Country, n = 7)
#infos des 7 premières lignes
```
```{r}
filter(Country, Ville == "France")
```

```{r}
filter(Country, Ville == "France")
#choisir les infos des lignes comportant la france
```
```{r}
filter(Country, Annee == "1992" & Ville == "Germany" )
```

#Pas de moyen de dire que la donnée n'existe pas? 

```{r}
filter(Country, is.na(Annee == "2022"))
#filtrer avec une valeur inexitante
```
```{r}
filter(Country, Ville == "Germany" & is.na (Annee == "2021"))
#tant qu'une valeur n'existe pas dans le tableau, on n'affiche pas"
```





